name: GitOps Kustomize PR
author: Eviive
description: Creates a pull request in a GitOps repository to update a Kustomize image tag

inputs:
  repository:
    description: The GitOps repository where the PR will be created
    required: true
  token:
    description: The token to access the GitOps repository
    required: true
  kustomize-version:
    description: The Kustomize version to update the image tag with
  kustomize-working-directory:
    description: The Kustomize working directory to update the image tag in
    required: true
  kustomize-image:
    description: The Kustomize image to update
    required: true
  docker-image:
    description: The Docker image to set in the Kustomize file
    required: true
  docker-tag:
    description: The Docker tag to set in the Kustomize file
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}

    - name: Setup Kustomize
      uses: eviive/actions/install/kustomize@main
      with:
        version: ${{ inputs.kustomize-version }}

    - name: Update image
      shell: bash
      working-directory: ${{ inputs.kustomize-working-directory }}
      run: kustomize edit set image ${{ inputs.kustomize-image }}=${{ inputs.docker-image }}:${{ inputs.docker-tag }}

    - name: Create PR
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.token }}
        commit-message: "ops(${{ inputs.kustomize-image }}): ${{ inputs.docker-tag }}"
        branch: release/${{ inputs.kustomize-image }}/${{ inputs.docker-tag }}
        title: "Release ${{ inputs.kustomize-image }}: ${{ inputs.docker-tag }}"
        body: ""
        assignees: ${{ github.actor }}
