name: Build and push to Docker Hub
author: Eviive
description: Builds a Docker image and pushes it to Docker Hub

inputs:
  docker-hub-username:
    description: Docker Hub username
    required: true
  docker-hub-token:
    description: Docker Hub token
    required: true
  docker-hub-repository:
    description: Docker Hub repository where the image will be pushed
    required: true
  lfs:
    description: Whether to use Git LFS
    default: false

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: ${{ inputs.lfs }}

    - name: Checkout LFS objects
      if: ${{ inputs.lfs == 'true' }}
      shell: bash
      run: git lfs checkout

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.docker-hub-username }}/${{ inputs.docker-hub-repository }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-hub-username }}
        password: ${{ inputs.docker-hub-token }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
