name: Remote Docker
author: Eviive
description: Sets up a connection to a remote Docker host

inputs:
  host:
    description: SSH host adress
    required: true
  username:
    description: SSH username
    required: true
  key:
    description: SSH private key
    required: true

runs:
    using: composite
    steps:
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: ${{ inputs.host }}
          private-key: ${{ inputs.key }}
          private-key-name: ${{ inputs.username }}-${{ inputs.host }}-key

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: ssh://${{ inputs.username }}@${{ inputs.host }}
