name: Remote Docker
author: Eviive
description: Sets up a connection to a remote Docker host

inputs:
  host:
    description: SSH host address
    required: true
  username:
    description: SSH username
    required: true
  key:
    description: SSH private key
    required: true

runs:
    using: composite
    steps:
      - name: SSH Setup
        uses: eviive/actions/ssh-setup@main
        with:
          host: ${{ inputs.host }}
          key: ${{ inputs.key }}

      - name: Create Docker remote context
        shell: bash
        run: docker context create remote --docker host=ssh://${{ inputs.username }}@${{ inputs.host }}

      - name: Use Docker remote context
        shell: bash
        run: docker context use remote
