name: Checkstyle
author: Eviive
description: Runs Checkstyle on the codebase and reports the results using reviewdog

inputs:
  version:
    description: The CheckStyle version to install
    required: true
  java-version:
    description: The Java version to install
    default: "21"
  config:
    description: The path to the Checkstyle configuration file
    default: config/checkstyle/checkstyle.xml
  properties:
    description: The properties file content to use with CheckStyle
    required: false
  workdir:
    description: The working directory relative to the root directory
    default: src/main/java

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin

    - name: Setup CheckStyle
      shell: bash
      run: wget -q -O checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-${{ inputs.version }}/checkstyle-${{ inputs.version }}-all.jar

    - name: Setup CheckStyle Properties
      shell: bash
      run: echo "${{ inputs.properties }}" > checkstyle.properties

    - name: Run CheckStyle
      shell: bash
      run: java -jar checkstyle.jar -c ${{ inputs.config }} -p checkstyle.properties ${{ inputs.workdir }}
