name: Setup Kustomize
author: Eviive
description: Sets up Kustomize

inputs:
  version:
    description: The Kustomize version to set up

runs:
  using: composite
  steps:
    - name: Setup Kustomize
      shell: bash
      run: |
        mkdir -p ${{ runner.temp }}/kustomize
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- ${{ inputs.version }} ${{ runner.temp }}/kustomize

    - name: Add Kustomize to PATH
      shell: bash
      run: echo "${{ runner.temp }}/kustomize" >> $GITHUB_PATH

    - name: Verify Kustomize Setup
      shell: bash
      run: kustomize version
