name: Prettier
author: Eviive
description: Runs Prettier on the codebase and reports the results using reviewdog

inputs:
  token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Prettier action
      uses: EPMatt/reviewdog-action-prettier@v1.2.0
      with:
        github_token: ${{ inputs.token }}
        reporter: github-pr-review
