name: SSH Setup
author: Eviive
description: Sets up an SSH connection to a remote host

inputs:
  host:
    description: SSH host adress
    required: true
  key:
    description: SSH private key
    required: true
  key-name:
    description: SSH private key name
    default: id_rsa

runs:
  using: composite
  steps:
    - name: Create .ssh directory
      shell: bash
      run: mkdir --parent ~/.ssh

    - name: Start SSH agent
      if: env.SSH_AGENT_PID == ''
      shell: bash
      run: |
        eval $(ssh-agent -s)
        echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV

    - name: Add SSH key
      shell: bash
      run: |
        echo "${{ inputs.key }}" > ~/.ssh/${{ inputs.key-name }}
        chmod 600 ~/.ssh/${{ inputs.key-name }}
        ssh-add ~/.ssh/${{ inputs.key-name }}

    - name: Add host to known hosts
      shell: bash
      run: ssh-keyscan -H ${{ inputs.host }} >> ~/.ssh/known_hosts
