name: npm Clean Install and Build
author: Eviive
description: Sets up Node.js and runs npm ci and npm run build

inputs:
  node-version:
    description: Node.js version
    required: true
    default: lts/*

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Clean install of the dependencies
      run: npm ci
      shell: bash

    - name: Build
      run: npm run build
      shell: bash