name: Validate Java

on:
  workflow_call:
    inputs:
      java-version:
        description: The Java version to use
        required: true
        type: string
      checkstyle:
        description: Whether to run CheckStyle
        type: boolean
        default: true
      checkstyle-version:
        description: The CheckStyle version to use
        type: string
      checkstyle-config:
        description: The path to the Checkstyle configuration file
        type: string
        default: config/checkstyle/checkstyle.xml
      checkstyle-properties:
        description: The CheckStyle properties file content to use
        type: string
        default: |
          config_loc=config/checkstyle
      checkstyle-working-directory:
        description: The CheckStyle working directory relative to the root directory
        type: string
        default: src/main/java

jobs:
  checkstyle:
    name: CheckStyle
    if: ${{ inputs.checkstyle }}
    uses: ./.github/workflows/validate-lint-checkstyle.yaml
    with:
      version: ${{ inputs.checkstyle-version }}
      java-version: ${{ inputs.java-version }}
      config: ${{ inputs.checkstyle-config }}
      properties: ${{ inputs.checkstyle-properties }}
      working-directory: ${{ inputs.checkstyle-working-directory }}
