name: ESLint
author: Eviive
description: Runs ESLint on the codebase

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: NPM clean install
      shell: bash
      run: npm ci

    - name: ESLint
      shell: bash
      run: npx eslint .
